"""Versioned public contract identifiers."""

CONFIG_SCHEMA_VERSION = 1
PLAN_FORMAT_VERSION = 1
MCP_CONTRACT_VERSION = 1

__all__ = [
    "CONFIG_SCHEMA_VERSION",
    "MCP_CONTRACT_VERSION",
    "PLAN_FORMAT_VERSION",
]
