"""Versioned public contract identifiers."""

CONFIG_SCHEMA_VERSION = 1
PROFILE_LAYER_VERSION = 2
PLAN_FORMAT_VERSION = 1
MCP_CONTRACT_VERSION = 3
CAPABILITY_FORMAT_VERSION = 1

__all__ = [
    "CONFIG_SCHEMA_VERSION",
    "CAPABILITY_FORMAT_VERSION",
    "MCP_CONTRACT_VERSION",
    "PLAN_FORMAT_VERSION",
    "PROFILE_LAYER_VERSION",
]
